Specify stdio option when invoking package manager
When this option isn't specified, `yarn` errors out (`npm` does not do this).

```js
const exec = require('child_process').execSync;

exec('yarn run postinstall', {});
```

```
node test.js || echo "Exit code: $?"
child_process.js:866
    throw err;
    ^

Error: Command failed: yarn run postinstall
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (/tmp/test/test.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 12204,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
Exit code: 1
```

```js
const exec = require('child_process').execSync;

exec('yarn run postinstall', { stdio: 'ignore' });
```

```
node test.js && echo "Exit code: $?"
Exit code: 0
```